/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.MegaSena;

/**
 *
 * @author Leo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private String url;
    private MegaSena api;
    private final Icon INFORMATION_MESSAGE = new ImageIcon(getToolkit().createImage(getClass().getResource("images/information.png")));
    private List<Integer> draw = new ArrayList<>();

    public Main() {
        initComponents();
        URL icon = this.getClass().getResource("images/icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(icon);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        bolao = new javax.swing.JLabel();
        btnTxt = new javax.swing.JLabel();
        lottery = new javax.swing.JLabel();
        btnGerar = new javax.swing.JLabel();
        numeroSorteado = new javax.swing.JLabel();
        txtNumeroSorteado = new javax.swing.JTextField();
        btnReceipt = new javax.swing.JLabel();
        quinas = new javax.swing.JLabel();
        btnQuina = new javax.swing.JLabel();
        btnQuadra = new javax.swing.JLabel();
        quadras = new javax.swing.JLabel();
        btnHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mega Sena");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/megasena.png"))); // NOI18N

        bolao.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        bolao.setForeground(new java.awt.Color(112, 112, 112));
        bolao.setText("Bolão:");

        btnTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/txt.png"))); // NOI18N
        btnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTxtMouseClicked(evt);
            }
        });

        lottery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/lottery-machine.png"))); // NOI18N
        lottery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lotteryMouseClicked(evt);
            }
        });

        btnGerar.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        btnGerar.setForeground(new java.awt.Color(112, 112, 112));
        btnGerar.setText("Gerar:");

        numeroSorteado.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        numeroSorteado.setForeground(new java.awt.Color(112, 112, 112));
        numeroSorteado.setText("Número Sorteado:");

        txtNumeroSorteado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNumeroSorteado.setForeground(new java.awt.Color(112, 112, 112));
        txtNumeroSorteado.setPreferredSize(new java.awt.Dimension(317, 40));
        txtNumeroSorteado.setSelectionColor(new java.awt.Color(87, 173, 86));
        txtNumeroSorteado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroSorteadoKeyTyped(evt);
            }
        });

        btnReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/receipt.png"))); // NOI18N
        btnReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReceiptMouseClicked(evt);
            }
        });

        quinas.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        quinas.setForeground(new java.awt.Color(112, 112, 112));
        quinas.setText("Quinas:");

        btnQuina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/quina.png"))); // NOI18N
        btnQuina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuinaMouseClicked(evt);
            }
        });

        btnQuadra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/quadra.png"))); // NOI18N
        btnQuadra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuadraMouseClicked(evt);
            }
        });

        quadras.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        quadras.setForeground(new java.awt.Color(112, 112, 112));
        quadras.setText("Quadras:");

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/information.png"))); // NOI18N
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(bolao)
                .addGap(18, 18, 18)
                .addComponent(btnTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerar)
                .addGap(18, 18, 18)
                .addComponent(lottery)
                .addGap(153, 153, 153))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(quinas)
                .addGap(18, 18, 18)
                .addComponent(btnQuina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quadras)
                .addGap(18, 18, 18)
                .addComponent(btnQuadra)
                .addGap(122, 122, 122))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(numeroSorteado)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReceipt)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHelp)
                .addGap(400, 400, 400))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lottery)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGerar)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bolao)
                                .addGap(8, 8, 8))
                            .addComponent(btnTxt))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReceipt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroSorteado))
                        .addGap(6, 6, 6)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuadra)
                    .addComponent(btnQuina)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quadras)
                            .addComponent(quinas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHelp)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroSorteadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroSorteadoKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            if (c != ',') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtNumeroSorteadoKeyTyped

    private void btnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTxtMouseClicked
        try {
            JFileChooser busca = new JFileChooser();
            busca.setDialogTitle("Carregar o bolão");
            busca.setFileFilter(new FileNameExtensionFilter(".txt", "txt"));
            busca.showOpenDialog(this);
            this.url = busca.getSelectedFile().getAbsolutePath();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro no caminho do arquivo", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnTxtMouseClicked

    private void btnHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/LeonardoGalves/mega-sena-bolaoapp"));
        } catch (IOException | URISyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnHelpMouseClicked

    private void lotteryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lotteryMouseClicked
        List<Integer> numeros = new ArrayList<>();
        for (int i = 0; i < 6; i++) {
            MegaSena.sorteio(numeros);
        }
        numeros.sort(null);
        JOptionPane.showMessageDialog(null, numeros, "Número gerado Aleatóriamente!", JOptionPane.INFORMATION_MESSAGE, this.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lotteryMouseClicked

    private void btnReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceiptMouseClicked
        if (this.url != null) {
            draw.clear();
            String[] sorteados = txtNumeroSorteado.getText().split(",");
            for (String val : sorteados) {
                draw.add(Integer.parseInt(val));
            }

            this.api = new MegaSena(this.draw);
            Scanner ler = null;
            try {
                ler = new Scanner(new File(this.url));
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Arquivo Não encontrado", JOptionPane.WARNING_MESSAGE);
            }

            while (ler.hasNextLine()) {
                List<Integer> numeros = new ArrayList<>();
                String linha = ler.nextLine();
                Scanner s = new Scanner(linha);
                s.useLocale(Locale.US);
                s.useDelimiter(";");
                String[] valores = linha.split(";");
                for (String valor : valores) {
                    numeros.add(s.nextInt());
                }
                this.api.setBolao(numeros);
                s.close();
            }
            ler.close();
            System.out.println("Números Lidos");
            this.api.getBolao();

            txtNumeroSorteado.setText("");

            if (this.api.getNumberWin().size() > 0) {
                Icon figura = new ImageIcon(getToolkit().createImage(getClass().getResource("images/party.png")));
                JOptionPane.showMessageDialog(null, this.api.getNumberWin(), "You Are the Champion!", JOptionPane.INFORMATION_MESSAGE, figura);
            }
        }else
            JOptionPane.showMessageDialog(null, "Carregue o arquivo do bolão primeiro", "Arquivo Não encontrado", JOptionPane.WARNING_MESSAGE, this.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnReceiptMouseClicked

    private void btnQuinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuinaMouseClicked
        if (this.api.haveBolao()) {
            this.api.setQuina();
            JOptionPane.showMessageDialog(null, "Número de Quinas: " + this.api.getQuina().size() + "\n" + this.api.getQuina(), "Quinas", JOptionPane.WARNING_MESSAGE, this.INFORMATION_MESSAGE);
        }else
            JOptionPane.showMessageDialog(null, "Informe os números sorteados primeiro", "Arquivo Não encontrado", JOptionPane.WARNING_MESSAGE, this.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnQuinaMouseClicked

    private void btnQuadraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuadraMouseClicked
        if (this.api.haveBolao()) {
            this.api.setQuadra();
            JOptionPane.showMessageDialog(null, "Número de Quadras: " + this.api.getQuadra().size() + "\n" + this.api.getQuadra(), "Quadras", JOptionPane.WARNING_MESSAGE, this.INFORMATION_MESSAGE);
        }else
            JOptionPane.showMessageDialog(null, "Informe os números sorteados primeiro", "Arquivo Não encontrado", JOptionPane.WARNING_MESSAGE, this.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnQuadraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bolao;
    private javax.swing.JLabel btnGerar;
    private javax.swing.JLabel btnHelp;
    private javax.swing.JLabel btnQuadra;
    private javax.swing.JLabel btnQuina;
    private javax.swing.JLabel btnReceipt;
    private javax.swing.JLabel btnTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel lottery;
    private javax.swing.JLabel numeroSorteado;
    private javax.swing.JLabel quadras;
    private javax.swing.JLabel quinas;
    private javax.swing.JTextField txtNumeroSorteado;
    // End of variables declaration//GEN-END:variables

}
